# ----
# Site

title: Code on the brain
url: "https://www.code-on-the-brain.com"
baseurl:
google_analytics_key:
newsletter_action: ""
disqus_shortname:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Technology blog by Tim Pope
author:
  name: Tim Pope
  email: tim@code-on-the-brain.com
  twitter: Tim_50_6f_70_65
social:
  name: Code on the brain
  links:
    - https://github.com/CloudCannon/treat-jekyll-template

# -----
# Build

paginate: 10
paginate_path: "/:num/"
permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      push_sidebar_down: true
      print_stylesheet: true
      comments: true
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"
      push_sidebar_down: true

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS
